# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d5ba50138a16208b86e82b854b7098a73561e17785c5d2d32b447628a3951a58f1819654a4300e57a53696c49724600719144d884da88e5b9c100235a914d053

test:
  secret_key_base: f123d572e37248d79f8f2636aa27f311b0b6dd90a8effdab18d716eddf14e784fe1c54b7873c1414eb3f2b5188695dd60f9a0973757761cb9171df4d28b8a656

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
